title: <p align="center"> Salsabila Fatin </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/salsabilafatinn/">LinkedIn</a> |
  <a href="https://github.com/salsabilafatinn">GitHub</a>
  </p>
  
  <p align="justify">
  I am a 6th semester student majoring in Statistics at Diponegoro University. I have interest in Data Science and Data Analytics.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
